version: '3.8'

services:
  backend:
    image: freeapi-server
    build:
      context: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/freeapi
      - /usr/src/freeapi/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

  frontend:
    build:
      context: ./frontend
    ports:
      - 5010:5010
    volumes:
      - ./frontend:/usr/src/freeapi-frontend-vue
      - /usr/src/freeapi-frontend-vue/node_modules

volumes:
  data:
